---
- hosts: all
  become: true
  roles:
    - role: mheap.wordpress
      database_name: wp_db
      database_user: wp_user
      database_password: wp@123
      wp_domain: book.example.com
      initial_post_title: Ansible Job Done!
      initial_post_content: >
        This is an example post. Change me to Say Something intresting!
      
  
  #roles:
    ## added dependencies roles to mheap.wordpress/meta/main.yml

  #tasks:
    # PHP
    ## moved tasks to mheap.php/tasks

    # MySQL
    ## moved tasks mheap.mysql/tasks
    ## moved templates to mheap.mysql/templates
    
    # nginx
    ## moved tasks to mheap.nginx/tasks
    ## moved templates to mheap.nginx/templates
    ## moved handlers to mheap.nginx/handlets

    # WordPress
    ## moved tasks to mheap.wordpress/tasks
    ## moved templates to mheap.wordpress/templates
    ## moved files to mheap.wordpress/files

    