---
- hosts: all
  become: true
  roles:
    - mheap.php
    - mheap.nginx
    - mheap.mysql
    - mheap.wordpress
  
  #tasks:
    # PHP
    ## moved tasks to mheap.php/tasks

    # MySQL
    ## moved tasks mheap.mysql/tasks
    ## moved templates to mheap.mysql/templates
    
    # nginx
    ## moved tasks to mheap.nginx/tasks
    ## moved templates to mheap.nginx/templates
    ## moved handlers to mheap.nginx/handlets

    # WordPress
    ## moved tasks to mheap.wordpress/tasks
    ## moved templates to mheap.wordpress/templates
    ## moved files to mheap.wordpress/files

    