---
- hosts: all
  sudo: yes
  tasks:

  - name: Install EPEL repo.
    yum: name=epel-release state=present

  - name: Import Remi GPG key.
    rpm_key: "key={{ item }} state=present"
    with_items:
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
  
  - name: Install Remi repo
    command: "rpm -Uvh --force {{ item.herf }} creates={{ item.creates }}"
    with_items:
      - herf: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        creates: "/etc/yum.repos.d/remi.repo"
  
  - name: Ensure firewalld is stopped (since this is a test server).
    service: name=firewalld state=stopped
  
  - name: Install Node.js and npm.
    yum: name=npm state=present enablerepo=epel
  
  - name: Install Forever (to run our Node.js app).
    npm: name=forever global=yes state=latest