---
- name: Delete AWS machines
  hosts: all
  connection: local
  gather_facts: False
  tasks:
    - ec2_remote_facts:
        region: us-west-2
        filters:
          "tag:Name=Demo"
        #  "instance-state-name": running
      register: instance_list

    - set_fact:
        instance_ids: "{{instance_list.instances|map(attribute='id')|list}}"
    
    - ec2:
        region: us-west-2
        instance_ids: "{{instance_ids}}"
        state: absent
